from __future__ import annotations

from .client import LLMTextClient, OpenAITextClient
from .core import ChatSessionProtocol, TextProviderProtocol
from .providers.base import BaseProvider
from .providers.openai import OpenAIProvider
from .providers.openai import (
    OPENAI_REASONING_EFFORT_HIGH,
    OPENAI_REASONING_EFFORT_LOW,
    OPENAI_REASONING_EFFORT_MEDIUM,
    OPENAI_REASONING_EFFORT_MINIMAL,
    OPENAI_REASONING_EFFORT_NONE,
    OPENAI_REASONING_EFFORT_XHIGH,
    OPENAI_REASONING_EFFORTS,
    OPENAI_SERVICE_TIER_AUTO,
    OPENAI_SERVICE_TIER_FLEX,
    OPENAI_SERVICE_TIERS,
    OPENAI_TEXT_VERBOSITIES,
    OPENAI_TEXT_VERBOSITY_HIGH,
    OPENAI_TEXT_VERBOSITY_LOW,
    OPENAI_TEXT_VERBOSITY_MEDIUM,
)
from .types import LLMTimings, LLMMessage, LLMResponse, LLMTokenUsage

try:
    from .providers.google import (
        GOOGLE_REASONING_EFFORT_HIGH,
        GOOGLE_REASONING_EFFORT_LOW,
        GOOGLE_REASONING_EFFORT_MEDIUM,
        GOOGLE_REASONING_EFFORT_MINIMAL,
        GOOGLE_REASONING_EFFORTS,
        GOOGLE_SERVICE_TIER_FLEX,
        GOOGLE_SERVICE_TIER_PRIORITY,
        GOOGLE_SERVICE_TIER_STANDARD,
        GOOGLE_SERVICE_TIERS,
        GoogleProvider,
    )
except ImportError:  # pragma: no cover - optional dependency in some test envs
    GOOGLE_REASONING_EFFORT_HIGH = "high"
    GOOGLE_REASONING_EFFORT_LOW = "low"
    GOOGLE_REASONING_EFFORT_MEDIUM = "medium"
    GOOGLE_REASONING_EFFORT_MINIMAL = "minimal"
    GOOGLE_REASONING_EFFORTS = (
        GOOGLE_REASONING_EFFORT_MINIMAL,
        GOOGLE_REASONING_EFFORT_LOW,
        GOOGLE_REASONING_EFFORT_MEDIUM,
        GOOGLE_REASONING_EFFORT_HIGH,
    )
    GOOGLE_SERVICE_TIER_STANDARD = "standard"
    GOOGLE_SERVICE_TIER_FLEX = "flex"
    GOOGLE_SERVICE_TIER_PRIORITY = "priority"
    GOOGLE_SERVICE_TIERS = (
        GOOGLE_SERVICE_TIER_STANDARD,
        GOOGLE_SERVICE_TIER_FLEX,
        GOOGLE_SERVICE_TIER_PRIORITY,
    )
    GoogleProvider = None

OpenAIChatSession = ChatSessionProtocol
REASONING_EFFORT_NONE = OPENAI_REASONING_EFFORT_NONE
REASONING_EFFORT_MINIMAL = OPENAI_REASONING_EFFORT_MINIMAL
REASONING_EFFORT_LOW = OPENAI_REASONING_EFFORT_LOW
REASONING_EFFORT_MEDIUM = OPENAI_REASONING_EFFORT_MEDIUM
REASONING_EFFORT_HIGH = OPENAI_REASONING_EFFORT_HIGH
REASONING_EFFORT_XHIGH = OPENAI_REASONING_EFFORT_XHIGH
REASONING_EFFORTS = OPENAI_REASONING_EFFORTS
SERVICE_TIER_AUTO = OPENAI_SERVICE_TIER_AUTO
SERVICE_TIER_FLEX = OPENAI_SERVICE_TIER_FLEX
SERVICE_TIERS = OPENAI_SERVICE_TIERS
TEXT_VERBOSITY_LOW = OPENAI_TEXT_VERBOSITY_LOW
TEXT_VERBOSITY_MEDIUM = OPENAI_TEXT_VERBOSITY_MEDIUM
TEXT_VERBOSITY_HIGH = OPENAI_TEXT_VERBOSITY_HIGH
TEXT_VERBOSITIES = OPENAI_TEXT_VERBOSITIES

__all__ = [
    "ChatSessionProtocol",
    "BaseProvider",
    "LLMMessage",
    "LLMResponse",
    "LLMTextClient",
    "LLMTimings",
    "LLMTokenUsage",
    "GoogleProvider",
    "GOOGLE_REASONING_EFFORT_MINIMAL",
    "GOOGLE_REASONING_EFFORT_LOW",
    "GOOGLE_REASONING_EFFORT_MEDIUM",
    "GOOGLE_REASONING_EFFORT_HIGH",
    "GOOGLE_REASONING_EFFORTS",
    "GOOGLE_SERVICE_TIER_STANDARD",
    "GOOGLE_SERVICE_TIER_FLEX",
    "GOOGLE_SERVICE_TIER_PRIORITY",
    "GOOGLE_SERVICE_TIERS",
    "OpenAIChatSession",
    "OpenAIProvider",
    "OpenAITextClient",
    "REASONING_EFFORT_NONE",
    "REASONING_EFFORT_MINIMAL",
    "REASONING_EFFORT_LOW",
    "REASONING_EFFORT_MEDIUM",
    "REASONING_EFFORT_HIGH",
    "REASONING_EFFORT_XHIGH",
    "REASONING_EFFORTS",
    "SERVICE_TIER_AUTO",
    "SERVICE_TIER_FLEX",
    "SERVICE_TIERS",
    "TEXT_VERBOSITY_LOW",
    "TEXT_VERBOSITY_MEDIUM",
    "TEXT_VERBOSITY_HIGH",
    "TEXT_VERBOSITIES",
    "TextProviderProtocol",
]
